const OpenAI = require("openai");
const { GoogleGenerativeAI } = require("@google/generative-ai");

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function generateContent(hotel) {
  const prompt = `Buat artikel travel blog pendek (2-3 kalimat) yang sangat menarik untuk Hotel: ${hotel.name}, Harga: ${hotel.price}, Rating: ${hotel.rating}/10. Gunakan gaya bahasa influencer travel.`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 200,
    });
    console.log("✅ Content generated by OpenAI");
    return response.choices[0].message.content;
  } catch (err) {
    console.warn("⚠️ OpenAI Limit, Switching to Gemini...");
    try {
      const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
      const result = await model.generateContent(prompt);
      console.log("✨ Content generated by Gemini (Fallback)");
      return result.response.text();
    } catch (geminiErr) {
      console.error("❌ SEMUA AI ERROR:", geminiErr.message);
      return `Nikmati pengalaman mewah di ${hotel.name}. Pilihan terbaik di Mumbai dengan harga ${hotel.price}!`;
    }
  }
}
module.exports = generateContent;
